arb-dir: lib/src/l10n/translations
template-arb-file: intl_ru.arb
output-localization-file: app_localizations.g.dart
output-dir: lib/src/l10n/generated
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_messages.txt
