name: app_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  talker_dio_logger: ^4.7.9
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.4.0
  surf_lint_rules: ^4.0.0
  talker: ^4.7.9
  talker_bloc_logger: ^4.7.9
  talker_flutter: ^4.7.9
  device_info_plus: ^11.3.0
  equatable: ^2.0.7
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10
  mask_text_input_formatter: ^2.9.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  retrofit_generator: ^9.2.0
  flutter_gen_runner: ^5.10.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf